Added hotkeys for easy switching between shaders and wallpapers

diff --git a/.local/bin/hyprdot-control-paper b/.local/bin/hyprdot-control-paper
--- a/.local/bin/hyprdot-control-paper
+++ b/.local/bin/hyprdot-control-paper
@@ -2,102 +2,144 @@
 
 usage() {
     cat << EOF
-Usage:  hyprdot-control-paper update status
-        hyprdot-control-paper set on|off|toggle
-        hyprdot-control-paper set back|next
+Usage:  hyprdot-control-paper get status|mode
+        hyprdot-control-paper set status on|off|toggle [save] 
+        hyprdot-control-paper set mode back|next [save]
+        hyprdot-control-paper set paper {paper} [save]
+        hyprdot-control-paper set restore
 EOF
     exit 1
 }
 
 PROCESS="hyprpaper"
-WALLPAPER_PATH="$HOME/.config/hypr/papers"
-CURRENT_WALLPAPER=$(hyprdot-settings read "hyprpaper.wallpaper")
-IS_ENABLED=$(hyprdot-settings read "hyprpaper.isEnabled")
+PAPERS_PATH="$HOME/.config/hypr/papers"
+PAPERS=($(ls "$PAPERS_PATH" | grep -v "current" | sort))
 
-get_status() {
-    is_process_running "$PROCESS" && echo "on" || echo "off"
+check_paper_exists() {
+    local paper="$1"
+    if [ ! -d "$PAPERS_PATH/$paper" ]; then
+        echo "Paper '$paper' not found."
+        exit 1
+    fi
 }
 
-get_wallpaper() {
-    echo $CURRENT_WALLPAPER
-}
 
-set_opacity() {
-    hyprctl keyword "decoration:fullscreen_opacity" "$1"
-    hyprctl keyword "decoration:active_opacity" "$1"
-    hyprctl keyword "decoration:inactive_opacity" "$1"
-}
-
-set_blur() {
-    hyprctl keyword "decoration:blur:enabled" "$1"
-}
-
-is_process_running() {
-    pgrep "$1" > /dev/null 2>&1
+is_enabled() {
+    pgrep "$PROCESS" > /dev/null 2>&1
     return $?
 }
 
-init() {
-    [ "$IS_ENABLED" = "true" ] && on || off
+restart() {
+    killall $PROCESS
+    $PROCESS > /dev/null 2>&1
+}
+
+refresh_symlink() {
+    local paper="$1"
+    rm -r "$PAPERS_PATH/current"
+    ln -s "$PAPERS_PATH/$paper" "$PAPERS_PATH/current"
+}
+
+restore() {
+    local status="$(load_status)"
+    local paper="$(load_mode)"
+
+    [ "$status" = "false" ] && {
+        off;
+        exit 0;
+    }
+
+    set_mode "$paper"
+}
+
+load_status() {
+    hyprdot-settings read "paper.isEnabled"
+}
+
+load_mode() {
+    hyprdot-settings read "paper.mode"
+}
+
+save_status() {
+    hyprdot-settings assign "paper.isEnabled" "$1"
+}
+
+save_mode() {
+    hyprdot-settings assign "paper.mode" "$1"
+}
+
+get_status() {
+    is_enabled
+    [ $? -eq 0 ] && echo "true" || echo "false"
+}
+
+get_mode() {
+    local current="$(basename "$(readlink -f "$PAPERS_PATH/current")")"
+    echo "$current"
+}
+
+set_mode() {
+    local paper="$1"
+
+    check_paper_exists "$paper"
+
+    waynot send "Paper" "$paper"
+    refresh_symlink "$paper"
+    restart
+
+    [ "$SAVE" -eq 1 ] && {
+        save_status "true"
+        save_mode "$paper";
+    }
 }
 
 on() {
-    hyprctl reload
-    $PROCESS &
-    hyprdot-settings assign "hyprpaper.isEnabled" "true"
-    waynot send "Paper" "${CURRENT_WALLPAPER^}"
+    set_mode "$(load_mode)"
 }
 
 off() {
-    set_opacity "1"
-    set_blur "false"
+    waynot send "Paper is off"
     killall $PROCESS
-    hyprdot-settings assign "hyprpaper.isEnabled" "false"
+
+    [ "$SAVE" -eq 1 ] && {
+        save_status "false"
+    }
 }
 
 toggle() {
-    is_process_running "$PROCESS" && off || on
+    is_enabled
+    [ $? -eq 0 ]  && off || on
+}
+
+navigate() {
+    local offset=$1
+
+    if [ ${#PAPERS[@]} -eq 0 ]; then
+        echo "No papers available."
+        exit 1
+    fi
+
+    for i in "${!PAPERS[@]}"; do
+        if [ "${PAPERS[$i]}" = "$(get_mode)" ]; then
+            local new_index=$(( (i + offset + ${#PAPERS[@]}) % ${#PAPERS[@]} ))
+            set_mode "${PAPERS[$new_index]}"
+            return
+        fi
+    done
 }
 
 back() {
-    local wallpapers=($(ls "$WALLPAPER_PATH" | grep -v "current"))
-    
-    for i in "${!wallpapers[@]}"; do
-        if [ "${wallpapers[$i]}" = "$CURRENT_WALLPAPER" ]; then
-            back_index=$(( (i + 1) % ${#wallpapers[@]} ))
-            back_wallpaper=${wallpapers[$next_index]}
-        fi
-    done
-
-    hyprdot-settings assign "hyprpaper.wallpaper" "$back_wallpaper"
-    CURRENT_WALLPAPER=$(hyprdot-settings read "hyprpaper.wallpaper")
-
-    rm -r "$WALLPAPER_PATH/current"
-    ln -s "$WALLPAPER_PATH/$back_wallpaper" "$WALLPAPER_PATH/current"
-
-    off
-    on
+    is_enabled
+    [ $? -eq 0 ] && navigate "-1"
 }
 
 next() {
-    local wallpapers=($(ls "$WALLPAPER_PATH" | grep -v "current"))
-    
-    for i in "${!wallpapers[@]}"; do
-        if [ "${wallpapers[$i]}" = "$CURRENT_WALLPAPER" ]; then
-            next_index=$(( (i + 1) % ${#wallpapers[@]} ))
-            next_wallpaper=${wallpapers[$next_index]}
-        fi
-    done
-
-    hyprdot-settings assign "hyprpaper.wallpaper" "$next_wallpaper"
-    CURRENT_WALLPAPER=$(hyprdot-settings read "hyprpaper.wallpaper")
-
-    rm -r "$WALLPAPER_PATH/current"
-    ln -s "$WALLPAPER_PATH/$next_wallpaper" "$WALLPAPER_PATH/current"
-
-    off
-    on
+    is_enabled
+    [ $? -eq 0 ] && navigate "+1"
 }
+
+SAVE=0
+[ "$4" = "save" ] && SAVE=1
 
 case "$1" in
     "get")
@@ -105,8 +147,8 @@ case "$1" in
             "status")
                 get_status
                 ;;
-            "wallpaper")
-                get_wallpaper
+            "mode")
+                get_mode
                 ;;
             *)
                 usage
@@ -115,25 +157,42 @@ case "$1" in
         ;;
     "set")
         case "$2" in
-            "init")
-                init
+            "status")
+                case "$3" in
+                    "on")
+                        on
+                        ;;
+                    "off")
+                        off
+                        ;;
+                    "toggle")
+                        toggle
+                        ;;
+                    *)      
+                        usage
+                        ;;
+                esac
                 ;;
-            "on")
-                on
+            "mode")
+                case "$3" in
+                    "back")
+                        back
+                        ;;
+                    "next")
+                        next
+                        ;;
+                    *)
+                        usage
+                        ;;
+                esac
                 ;;
-            "off")
-                off
+            "paper")
+                set_mode "$3"
                 ;;
-            "toggle")
-                toggle
+            "restore")
+                restore
                 ;;
-            "back")
-                back
-                ;;
-            "next")
-                next
-                ;;
-            *)
+            *)      
                 usage
                 ;;
         esac
diff --git a/.local/bin/hyprdot-control-shader b/.local/bin/hyprdot-control-shader
--- a/.local/bin/hyprdot-control-shader
+++ b/.local/bin/hyprdot-control-shader
@@ -2,98 +2,140 @@
 
 usage() {
     cat << EOF
-Usage:  hyprdot-control-shader get mode
-        hyprdot-control-shader set off|on|toggle
-        hyprdot-control-shader set back|next
+Usage:  hyprdot-control-shader get status|mode
+        hyprdot-control-shader set status on|off|toggle [save] 
+        hyprdot-control-shader set mode back|next [save]
+        hyprdot-control-shader set shader {shader} [save]
+        hyprdot-control-shader set restore
 EOF
+    exit 1
 }
 
-SHADERS="$HOME/.config/hypr/shaders/"
+SHADERS_PATH="$HOME/.config/hypr/shaders"
+SHADERS=($(ls "$SHADERS_PATH" | grep -v "current" | sort))
 
-get_current_shader() {
-    hyprdot-settings read "shader.mode"
-}
-
-set_shader() {
-    hyprctl keyword "decoration:screen_shader" "$1"
-}
-
-get_status() {
-    echo $(hyprctl getoption "decoration:screen_shader" | grep "set: true")
+check_shader_exists() {
+    local shader="$1"
+    if [ ! -f "$SHADERS_PATH/$shader" ]; then
+        echo "Paper '$shader' not found."
+        exit 1
+    fi
 }
 
 is_enabled() {
-    get_status | grep -q "true" && return 1 || return 0
+    hyprctl getoption "decoration:screen_shader" | grep -q "set: true" && return 1 || return 0
 }
 
-off() {
-    waynot send "Shader" "Reset"
-    hyprctl reload
+restore() {
+    local status="$(load_status)"
+    local shader="$(load_mode)"
+
+    [ "$status" = "false" ] && {
+        off;
+        exit 0;
+    }
+
+    set_mode "$shader"
+}
+
+load_status() {
+    hyprdot-settings read "shader.isEnabled"
+}
+
+load_mode() {
+    hyprdot-settings read "shader.mode"
+}
+
+save_status() {
+    local status="$1"
+    hyprdot-settings assign "shader.isEnabled" "$status"
+}
+
+save_mode() {
+    local shader="$1"
+    hyprdot-settings assign "shader.mode" "$shader"
+}
+
+get_status() {
+    is_enabled
+    [ $? -eq 1 ] && echo "true" || echo "false"
+}
+
+get_mode() {
+    local path=$(hyprctl getoption "decoration:screen_shader" | grep "str: " | awk -F':' '{print $2}' | xargs)
+    echo "$(basename "$path")"
+}
+
+set_mode() {
+    local shader="$1"
+
+    check_shader_exists "$shader"
+
+    waynot send "Shader" "$shader"
+    hyprctl keyword "decoration:screen_shader" "$SHADERS_PATH/$shader"
+
+    [ "$SAVE" -eq 1 ] && {
+        save_status "true"
+        save_mode "$shader";
+    }
 }
 
 on() {
-    waynot send "Shader" "$(get_current_shader)"
-    set_shader "$SHADERS/$(get_current_shader)"
+    set_mode "$(load_mode)"
+}
+
+off() {
+    waynot send "Shader is off"
+    hyprctl reload
+
+    [ "$SAVE" -eq 1 ] && {
+        save_status "false"
+    }
 }
 
 toggle() {
     is_enabled
-    [ $? -eq 1 ] && off || on
+    [ $? -eq 1 ]  && off || on
+}
+
+navigate() {
+    local offset=$1
+
+    if [ ${#SHADERS[@]} -eq 0 ]; then
+        echo "No shaders available."
+        exit 1
+    fi
+
+    for i in "${!SHADERS[@]}"; do
+        if [ "${SHADERS[$i]}" = "$(get_mode)" ]; then
+            local new_index=$(( (i + offset + ${#SHADERS[@]}) % ${#SHADERS[@]} ))
+            set_mode "${SHADERS[$new_index]}"
+            return
+        fi
+    done
 }
 
 back() {
     is_enabled
-    [ $? -eq 0 ] && { on; exit 0; }
-
-    local shaders=($(ls "$SHADERS" | grep -v "current"))
-
-    if [ ${#shaders[@]} -eq 0 ]; then
-        echo "No shaders available."
-        exit 1
-    fi
-
-    for i in "${!shaders[@]}"; do
-        if [ "${shaders[$i]}" = "$(get_current_shader)" ]; then
-            back_index=$(( (i - 1 + ${#shaders[@]}) % ${#shaders[@]} ))
-            back_shader=${shaders[$back_index]}
-        fi
-    done
-
-    hyprdot-settings assign "shader.mode" "$back_shader"
-    set_shader "$SHADERS/$back_shader"
-
-    waynot send "Shader" "$back_shader"
+    [ $? -eq 1 ] && navigate "-1"
 }
 
 next() {
     is_enabled
-    [ $? -eq 0 ] && { on; exit 0; }
-
-    local shaders=($(ls "$SHADERS" | grep -v "current"))
-
-    if [ ${#shaders[@]} -eq 0 ]; then
-        echo "No shaders available."
-        exit 1
-    fi
-
-    for i in "${!shaders[@]}"; do
-        if [ "${shaders[$i]}" = "$(get_current_shader)" ]; then
-            next_index=$(( (i + 1) % ${#shaders[@]} ))
-            next_shader=${shaders[$next_index]}
-        fi
-    done
-
-    hyprdot-settings assign "shader.mode" "$next_shader"
-    set_shader "$SHADERS/$next_shader"
-
-    waynot send "Shader" "$next_shader"
+    [ $? -eq 1 ] && navigate "+1"
 }
+
+SAVE=0
+[ "$4" = "save" ] && SAVE=1
 
 case "$1" in
     "get")
         case "$2" in
+            "status")
+                get_status
+                ;;
             "mode")
-                echo $(get_current_shader)
+                get_mode
                 ;;
             *)
                 usage
@@ -102,22 +144,42 @@ case "$1" in
         ;;
     "set")
         case "$2" in
-            "off")
-                off
+            "status")
+                case "$3" in
+                    "on")
+                        on
+                        ;;
+                    "off")
+                        off
+                        ;;
+                    "toggle")
+                        toggle
+                        ;;
+                    *)      
+                        usage
+                        ;;
+                esac
                 ;;
-            "on")
-                on
+            "mode")
+                case "$3" in
+                    "back")
+                        back
+                        ;;
+                    "next")
+                        next
+                        ;;
+                    *)
+                        usage
+                        ;;
+                esac
                 ;;
-            "toggle")
-                toggle
+            "shader")
+                set_mode "$3"
                 ;;
-            "back")
-                back
+            "restore")
+                restore
                 ;;
-            "next")
-                next
-                ;;
-            *)
+            *)      
                 usage
                 ;;
         esac
